# Python Programming Revision

This notebook accompanies the Python Programming Revision lecture and includes examples of key Python programming concepts. The aim of these examples is to familiarize students with Python fundamentals and introduce scientific libraries, such as Numpy, Pandas, and Plotly, which will be used in subsequent lectures.

# Prerequisites
Before starting this notebook, you should have jupyter notebook, numpy, pandas and plotly installed. If you haven't installed these libraries yet, you can do so by running the following commands to create a new conda environment and install the required libraries:
```bash
conda create -n python_intro python=3.12
conda activate python_intro
conda install numpy pandas plotly
```

# Python's key features
In this section you will learn about Python's key features, such as:
- f-strings,
- data structures, 
- logic, 
- control flow, 
- functions, 
- list and dictionary comprehensions,
- exceptions handling, 
- assertions.

In [55]:
# Classic Hello World example:
print("Hello World!")

Hello World!


In [56]:
# Using f-strings:
name = "Alice"
score = 90
print(f"{name} scored {score} in the test.")  # Output: Alice scored 90 in the test.

Alice scored 90 in the test.


In [57]:
# Complex expression inside f-string:
print(f"Half of {score} is {score / 2}.")

Half of 90 is 45.0.


In [58]:
# Creating and adding values to the list:
my_list = [10, 20, 30, 40, 50]
print(my_list)  # Output: [10, 20, 30, 40, 50]
my_list.append(60)
print(my_list)  # Output: [10, 20, 30, 40, 50, 60]

# Deleting fifth element
my_list.pop(4)
print(my_list)  # Output: [10, 20, 30, 40, 60]
# Deleting a specific element from the list:
my_list.remove(60)
print(my_list) # Output: [10, 20, 30, 40, 60]

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 60]
[10, 20, 30, 40]


In [59]:
# Accessing Elements and Slicing:
print(my_list[1])  # Output: 20 (second element)
print(my_list[-1])  # Output: 50 (last element)
print(my_list[:3])  # Output: [10, 20, 30] (first three elements)
print(my_list[1:4])  # Output: [20, 30, 40] (second, third and fourth elements)

20
40
[10, 20, 30]
[20, 30, 40]


In [60]:
# Using for loop to iterate over a list:
for item in my_list:
    print(item)

10
20
30
40


In [1]:
# Creating and accessing a dictionary:
student_scores = {"Alice": 85, "Bob": 92, "Charlie": 78}
print(student_scores)  # Output: {'Alice': 85, 'Bob': 92, 'Charlie': 78}
print(student_scores["Bob"])  # Output: 92 (Bob's score)
print(student_scores.get("Charlie"))  # Output: 78 (Charlie's score)
print(student_scores.values()) # Output: dict_values([85, 92, 78])
print(student_scores.keys()) # Output: dict_keys(['Alice', 'Bob', 'Charlie'])

{'Alice': 85, 'Bob': 92, 'Charlie': 78}
92
78
dict_values([85, 92, 78])
dict_keys(['Alice', 'Bob', 'Charlie'])


In [62]:
# Adding a new key-value pair:
student_scores["David"] = 90
print(student_scores)  # Output: {'Alice': 85, 'Bob': 92, 'Charlie': 78, 'David': 90}

# Updating an existing value:
student_scores["Charlie"] = 80
print(student_scores)  # Output: {'Alice': 85, 'Bob': 92, 'Charlie': 80, 'David': 90}

# Deleting a key-value pair:
del student_scores["Alice"]
print(student_scores)  # Output: {'Bob': 92, 'Charlie': 80, 'David': 90}

{'Alice': 85, 'Bob': 92, 'Charlie': 78, 'David': 90}
{'Alice': 85, 'Bob': 92, 'Charlie': 80, 'David': 90}
{'Bob': 92, 'Charlie': 80, 'David': 90}


In [63]:
# Iterating over a dictionary with for loop:
for key, value in student_scores.items():
    print(f"{key} scored {value}")

Bob scored 92
Charlie scored 80
David scored 90


In [64]:
# If-else statement:
score = 85
if score > 90:
    print("Excellent")
elif score > 80:
    print("Good")
else:
    print("Needs Improvement")

Good


In [65]:
# for loop with range:
for i in range(5):
    print(f"Number: {i}")

Number: 0
Number: 1
Number: 2
Number: 3
Number: 4


In [66]:
# while loop:
count = 0
while count < 5:
    print(f"Count: {count}")
    count += 1

Count: 0
Count: 1
Count: 2
Count: 3
Count: 4


In [67]:
# Logical operators (and, or, not):

# and: True if both conditions are true
score = 85
attendance = 90
if score > 80 and attendance > 85:
    print("Eligible for award")

# or: True if at least one condition is true
# Checking multiple conditions using `or`
if score > 90 or attendance > 85:
    print("Considered for award")

# not: True if the condition is false
if not score < 80:
    print("Score does not need improvement")

Eligible for award
Considered for award
Score does not need improvement


In [68]:
# Functions:
def greet(name):
    return f"Hello, {name}!"

print(greet("Alice"))  # Output: Hello, Alice!

Hello, Alice!


In [69]:
# Functions with default arguments:
def greet(name="Alice"):
    return f"Hello, {name}!"

print(greet())  # Output: Hello, Alice!
print(greet("Bob"))  # Output: Hello, Bob!

Hello, Alice!
Hello, Bob!


In [70]:
# Functions with multiple arguments:
def greet(name, message):
    return f"{message}, {name}!"

print(greet("Alice", "Good Morning"))  # Output: Good Morning, Alice!

Good Morning, Alice!


In [71]:
# Functions with multiple return values:
def get_student_info():
    name = "Alice"
    score = 85
    return name, score

student_name, student_score = get_student_info()
print(f"{student_name} scored {student_score}")  # Output: Alice scored 85
student_information = get_student_info()
print(f"{student_information[0]} scored {student_information[1]}")  # Output: Alice scored 85

Alice scored 85
Alice scored 85


In [2]:
# Lambda functions:
multiply = lambda x, y: x * y
print(multiply(5, 4))  # Output: 20

# Using lambda function with map
numbers = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, numbers))
print(squared)  # Output: [1, 4, 9, 16, 25]

20
[1, 4, 9, 16, 25]


In [6]:
# List comprehension:
squares = [x**2 for x in range(1, 6)]
print(squares) # Output: [1, 4, 9, 16, 25]

# List comprehension for filtering:
even_numbers = [x for x in range(1, 6) if x % 2 == 0]
print(even_numbers)  # Output: [2, 4]

# List comprehension with condition:
even_squares = [x**2 for x in range(1, 6) if x % 2 == 0]
print(even_squares)  # Output: [4, 16]

[1, 4, 9, 16, 25]
[2, 4]
[4, 16]


In [7]:
# Dictionary comprehension:
squares_dict = {x: x**2 for x in range(1, 6)}
print(squares_dict)

# Dictionary comprehension with condition:
even_squares_dict = {x: x**2 for x in range(1, 6) if x % 2 == 0}
print(even_squares_dict)

# Swap keys and values in an existing dictionary
original_dict = {'a': 1, 'b': 2, 'c': 3}
swapped_dict = {v: k for k, v in original_dict.items()}
print(swapped_dict)  # Output: {1: 'a', 2: 'b', 3: 'c'}


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
{2: 4, 4: 16}
{1: 'a', 2: 'b', 3: 'c'}


In [75]:
# Assertions:
def add(a, b):
    return a + b

assert add(3, 4) == 7  # Passes, as 3 + 4 is 7
# assert add(3, 4) == 8  # Would raise an AssertionError, you can uncomment and run to see the error

In [76]:
# Exceptions handling:
try:
    result = 10 / 0  # Will raise ZeroDivisionError
except ZeroDivisionError:
    print("You can't divide by zero!")

You can't divide by zero!


In [77]:
# Catching multiple exceptions:
try:
    num = int(input("Enter a number: "))  # Could raise ValueError
    result = 10 / num  # Could raise ZeroDivisionError
except ValueError:
    print("Invalid input! Please enter a number.")
except ZeroDivisionError:
    print("You can't divide by zero!")

Invalid input! Please enter a number.


In [78]:
# Catching all exceptions:
try:
    result = 10 / 0  # Will raise ZeroDivisionError
except Exception as e:
    print(f"An error occurred: {e}")

An error occurred: division by zero


In [79]:
# Raising exceptions manually:
def check_positive(num):
    if num < 0:
        raise ValueError("The number must be positive.")
    return num

try:
    check_positive(-10)
except ValueError as e:
    print(e)

The number must be positive.


# Libraries for Data Science
In this section you will learn about Python libraries used in Data Science, such as:
- Numpy,
- Pandas,
- Plotly.

In [9]:
# Importing libraries:
import numpy as np
import pandas as pd
import plotly.express as px
import random

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [10]:
# Random Functions
# You can set a seed to generate the same random numbers:
random.seed(0)

# Generate a random float:
print(random.random())  # Output: Random float between 0 and 1
print(random.uniform(1, 10))  # Output: Random float between 1 and 10

# Generate a random integer:
print(random.randint(1, 10))  # Output: Random integer between 1 and 10

# Generate a random sample from a list:
my_list = [10, 20, 30, 40, 50]
print(random.sample(my_list, 2))  # Output: Random sample of 2 elements
print(random.choice(my_list))  # Output: Random choice from the list
print(random.choices(my_list, k=2))  # Output: Random choices of 2 elements

0.8444218515250481
7.821589626462722
7
[10, 30]
50
[30, 50]


In [11]:
# You can set a new numpy seed:
np.random.seed(0)

In [12]:
# Creating Numpy arrays:
# 1D array (vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:\n", arr_1d)

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D array:\n", arr_2d)

# 3D array (tensor)
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", arr_3d)

1D array:
 [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# Checking the type of the arrays
print(type(arr_1d))  # Output: <class 'numpy.ndarray'>
print(type(arr_2d))  # Output: <class 'numpy.ndarray'>

# Shape of the arrays
print("Shape of 1D array:", arr_1d.shape)  # Output: (5,)
print("Shape of 2D array:", arr_2d.shape)  # Output: (3, 3)
print("Shape of 3D array:", arr_3d.shape)  # Output: (2, 2, 2)

# Number of dimensions (ndim) of the arrays
print("Dimensions of 1D array:", arr_1d.ndim)  # Output: 1
print("Dimensions of 2D array:", arr_2d.ndim)  # Output: 2
print("Dimensions of 3D array:", arr_3d.ndim)  # Output: 3

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Shape of 1D array: (5,)
Shape of 2D array: (3, 3)
Shape of 3D array: (2, 2, 2)
Dimensions of 1D array: 1
Dimensions of 2D array: 2
Dimensions of 3D array: 3


In [14]:
# Basic operations on Numpy arrays:
# Element-wise addition
arr_sum = arr_1d + 2  # Adds 2 to each element
print("1D array after addition:\n", arr_sum)

# Element-wise multiplication
arr_product = arr_2d * 2  # Multiplies each element by 2
print("2D array after multiplication:\n", arr_product)

# Matrix multiplication
arr_mult = np.dot(arr_2d, arr_2d)  # 2D matrix multiplication
print("Matrix multiplication result:\n", arr_mult)

1D array after addition:
 [3 4 5 6 7]
2D array after multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix multiplication result:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [15]:
# Accessing elements in a 1D array
print("Element at index 2 in 1D array:", arr_1d[2])  # Output: 3

# Accessing elements in a 2D array
print("Element at row 1, col 2 in 2D array:", arr_2d[1, 2])  # Output: 6

# Slicing 1D array
print("Slicing 1D array [1:4]:", arr_1d[1:4])  # Output: [2, 3, 4]

# Slicing 2D array
print("Slicing 2D array [0:2, 1:3]:\n", arr_2d[0:2, 1:3])

Element at index 2 in 1D array: 3
Element at row 1, col 2 in 2D array: 6
Slicing 1D array [1:4]: [2 3 4]
Slicing 2D array [0:2, 1:3]:
 [[2 3]
 [5 6]]


In [16]:
# Array Broadcasting:
# Broadcasting a scalar to a 2D array
arr_broadcast = arr_2d + 10
print("2D array after broadcasting addition:\n", arr_broadcast)

# Broadcasting a 1D array to a 2D array
arr_2d_broadcast = arr_2d + arr_1d[:3]  # arr_1d[:3] = [1, 2, 3]
print("Broadcasted 2D array:\n", arr_2d_broadcast)

2D array after broadcasting addition:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Broadcasted 2D array:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [17]:
# Creating Arrays with Special Functions
# Array of zeros
arr_zeros = np.zeros((3, 3))
print("Array of zeros:\n", arr_zeros)

# Array of ones
arr_ones = np.ones((2, 2))
print("Array of ones:\n", arr_ones)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1.]
 [1. 1.]]


In [18]:
# Array of evenly spaced values (like a range)
arr_range = np.arange(0, 10, 2)
print("Array with range 0 to 10 with step 2:", arr_range)

# Array of random values
arr_random = np.random.random((2, 3))
print("Array of random values:\n", arr_random)

Array with range 0 to 10 with step 2: [0 2 4 6 8]
Array of random values:
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [89]:
# Combining Arrays
# Stacking arrays vertically
arr_vstack = np.vstack((arr_1d, arr_1d))
print("Vertically stacked array:\n", arr_vstack)

# Stacking arrays horizontally
arr_hstack = np.hstack((arr_1d, arr_1d))
print("Horizontally stacked array:\n", arr_hstack)

Vertically stacked array:
 [[1 2 3 4 5]
 [1 2 3 4 5]]
Horizontally stacked array:
 [1 2 3 4 5 1 2 3 4 5]


In [91]:
# Numpy functions for numerical analysis
arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))  # Output: 3.0 (mean)
print(np.std(arr))   # Output: 1.414... (standard deviation)
print(np.sum(arr))   # Output: 15 (sum of all elements)
print(np.max(arr))   # Output: 5 (maximum value)

3.0
1.4142135623730951
15
5


In [90]:
# Vectorization
# Without vectorization (using a Python loop)
arr = np.array([1, 2, 3, 4, 5])
squared = np.zeros_like(arr)

for i in range(len(arr)):
    squared[i] = arr[i] ** 2

print(squared)  # Output: [ 1  4  9 16 25]

# With vectorization (using NumPy's array operations)
squared_vectorized = arr ** 2
print(squared_vectorized)  # Output: [ 1  4  9 16 25]

[ 1  4  9 16 25]
[ 1  4  9 16 25]


In [106]:
# Creating a Pandas DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "Score": [85, 90, 88, 92]
}
df = pd.DataFrame(data)
print(df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88
3    David   40     92


In [107]:
# Reading a CSV file
df = pd.read_csv("week_1_data.csv")
# Displaying the first few rows of the DataFrame
print(df.head())

    Name  Age  Score  Hours_Studied
0  Alice   22     85              4
1    Tom   21     90              5
2    Bob   20     88              4
3   John   33     70              3
4   Kate   30     95              6


In [108]:
# Displaying first 10 rows of the DataFrame
print(df.head(10))

# Displaying the last few rows of the DataFrame
print(df.tail())

# Displaying the columns of the DataFrame
print(df.columns)

# Displaying the shape of the DataFrame
print(df.shape)

     Name  Age  Score  Hours_Studied
0   Alice   22     85              4
1     Tom   21     90              5
2     Bob   20     88              4
3    John   33     70              3
4    Kate   30     95              6
5  Selena   27     90              5
6    Adam   28     98              7
7   Nancy   21     60              3
8    Mary   24     95              7
9  Andrew   35     60              2
       Name  Age  Score  Hours_Studied
15   Steven   29     85              4
16   Audrey   31     90              6
17    Julia   26     92              6
18     Lisa   27     65              3
19  Richard   30     78              4
Index(['Name', 'Age', 'Score', 'Hours_Studied'], dtype='object')
(20, 4)


In [109]:
# DataFrame operations
# Accessing columns
print(df[["Name", "Age"]])

# Filtering rows based on a condition
print(df[df["Age"] > 30])

# Sorting the DataFrame
df_sorted = df.sort_values("Score", ascending=False)
print(df_sorted)

        Name  Age
0      Alice   22
1        Tom   21
2        Bob   20
3       John   33
4       Kate   30
5     Selena   27
6       Adam   28
7      Nancy   21
8       Mary   24
9     Andrew   35
10  Jennifer   32
11    Robert   30
12   Matthew   21
13      Mark   31
14   Anthony   22
15    Steven   29
16    Audrey   31
17     Julia   26
18      Lisa   27
19   Richard   30
        Name  Age  Score  Hours_Studied
3       John   33     70              3
9     Andrew   35     60              2
10  Jennifer   32     55              3
13      Mark   31     88              5
16    Audrey   31     90              6
        Name  Age  Score  Hours_Studied
6       Adam   28     98              7
4       Kate   30     95              6
8       Mary   24     95              7
17     Julia   26     92              6
12   Matthew   21     92              7
5     Selena   27     90              5
16    Audrey   31     90              6
1        Tom   21     90              5
13      Mark   31     

In [110]:
# Saving the DataFrame to a CSV file
df_sorted.to_csv("week_1_data_sorted.csv", index=False)

In [119]:
# Plotting with Plotly
# Basic scatter plot
fig = px.scatter(df, x='Name', y='Score', title='Student Scores by Name (scatter plot)')
fig.show()

In [112]:
# Adding color and size based on another variable
fig = px.scatter(df, x='Name', y='Score', size='Hours_Studied', color='Hours_Studied',
                 title='Student Scores and Hours Studied', hover_name='Name')
fig.show()

In [113]:
# Basic bar plot
fig = px.bar(df, x='Name', y='Score', title='Student Scores by Name (bar plot)')
fig.show()

In [114]:
# Customizing bar colors and adding hover information on sorted data
fig = px.bar(df_sorted, x='Name', y='Score', title='Student Scores by Name (sorted bar plot)',
             color='Hours_Studied', hover_name='Name')
fig.show()

In [115]:
# Histogram
fig = px.histogram(df, x='Score', nbins=5, title='Student Scores Distribution (histogram)')
fig.show()

In [116]:
# Line plot
time_data = {'Week': [1, 2, 3, 4, 5],
             'Score': [75, 80, 82, 85, 90]}
df_time = pd.DataFrame(time_data)

fig = px.line(df_time, x='Week', y='Score', title='Score Trend Over Time', markers=True)
fig.show()

In [117]:
# Customizing the line plot
fig.update_layout(
    title='Student Scores Trend Over Time',
    xaxis_title='Week Number',
    yaxis_title='Score Value'
)
fig.update_layout(template='plotly_dark')
fig.show()
# Save the plot to an HTML file
fig.write_html("student_scores.html")

# Comprehensive Coding Exercise - Live Coding
This task combines lists, dictionaries, functions, Numpy, Pandas, and Plotly.

Problem Statement:
- Generate 10 random student scores.
- Create a function to calculate the average score.
- Store student names and scores in a Pandas DataFrame.
- Filter students who scored above the average.
- Visualize the data using Plotly.

In [118]:
import numpy as np
import pandas as pd
import plotly.express as px
from random import randint

# 1. Generate random student scores
students = ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack']
scores = [randint(50, 100) for _ in range(10)]

# 2. Function to calculate average score
def calculate_average(scores):
    return np.mean(scores)

average_score = calculate_average(scores)
print(f"Average score: {average_score}")

# 3. Create a DataFrame
data = {'Name': students, 'Score': scores}
df = pd.DataFrame(data)

# 4. Filter students with scores above average
above_average = df[df['Score'] > average_score]
print(above_average)

# 5. Visualize results with Plotly
fig = px.bar(above_average, x='Name', y='Score', title='Students Scoring Above Average')
fig.show()

Average score: 75.8
    Name  Score
1    Bob     89
3  David     84
4    Eve     95
5  Frank     88
9   Jack     96
